spring:
  datasource:
    url: jdbc:h2:mem:ecom;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  level:
    root: INFO

# Kafka bootstrap (change as needed)
kafka:
  bootstrap-servers: localhost:9092
